name: WF04 - Deploy MCP Server to Azure
on:
  workflow_dispatch:

jobs:
  build-push-update:
    name: Build, Push Docker Image to ACR and Update Container App
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Azure Login
        uses: ./.github/actions/azure-login
        with:
          creds: ${{ secrets.INFRA_AZURE_SERVICE_PRINCIPAL_INFO }}

      - name: Build and Push Docker Image to ACR
        uses: ./.github/actions/acr-build-push
        with:
          acrName: ${{ vars.INFRA_AZURE_ACR_NAME }}
          imageName: ${{ vars.INFRA_MCPSERVER_IMAGE_NAME }}
          imageVersion: ${{ vars.INFRA_MCPSERVER_IMAGE_VERSION }}
          workingDir: ./mcp-server
          dockerfile: docker/Dockerfile

      - name: Update Azure Container App with New Image
        uses: ./.github/actions/containerapp-update-image
        with:
          resourceGroup: ${{ vars.INFRA_AZURE_RESOURCEGROUP_NAME }}
          containerAppName: ${{ vars.INFRA_AZURE_CONTAINERAPP_MCPSERVER_NAME }}
          acrName: ${{ vars.INFRA_AZURE_ACR_NAME }}
          imageName: ${{ vars.INFRA_MCPSERVER_IMAGE_NAME }}
          imageVersion: ${{ vars.INFRA_MCPSERVER_IMAGE_VERSION }}